# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import module_pb2 as module__pb2


class ModuleStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.runModule = channel.unary_unary(
                '/module.Module/runModule',
                request_serializer=module__pb2.Request.SerializeToString,
                response_deserializer=module__pb2.Reply.FromString,
                )


class ModuleServicer(object):
    """The greeting service definition.
    """

    def runModule(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'runModule': grpc.unary_unary_rpc_method_handler(
                    servicer.runModule,
                    request_deserializer=module__pb2.Request.FromString,
                    response_serializer=module__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'module.Module', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Module(object):
    """The greeting service definition.
    """

    @staticmethod
    def runModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/module.Module/runModule',
            module__pb2.Request.SerializeToString,
            module__pb2.Reply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
